### ISSUE TITLE
Crash with DNSSD on app destruction

### ISSUE THREAD

**Issue by maximilize** [balthazar/react-native-zeroconf#173]
This crash happens always when I reload the Javascript bundle in a release app.

To prevent this crash, replace `Exception` with `Throwable` in `ZeroconfModule.onCatalystInstanceDestroy()` works.

```
01-28 01:31:12.210 13740 13774 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-28 01:31:12.210 13740 13774 E AndroidRuntime: Process: com.app.test, PID: 13740
01-28 01:31:12.210 13740 13774 E AndroidRuntime: java.lang.InternalError: cannot instantiate DNSSDjava.lang.ClassNotFoundException: com.github.druk.dnssd.AppleDNSSD
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.github.druk.dnssd.InternalDNSSD.<clinit>(InternalDNSSD.java:491)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.github.druk.dnssd.InternalDNSSD.init(InternalDNSSD.java:91)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.github.druk.dnssd.DNSSD.<init>(DNSSD.java:90)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.github.druk.dnssd.DNSSD.<init>(DNSSD.java:85)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.github.druk.dnssd.DNSSDBindable.<init>(DNSSDBindable.java:34)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.github.druk.rx2dnssd.Rx2DnssdBindable.<init>(Rx2DnssdBindable.java:32)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.balthazargronon.RCTZeroconf.rx2dnssd.DnssdImpl.<init>(DnssdImpl.java:52)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.balthazargronon.RCTZeroconf.ZeroConfImplFactory.getOrCreateImpl(ZeroConfImplFactory.java:39)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.balthazargronon.RCTZeroconf.ZeroConfImplFactory.getZeroconf(ZeroConfImplFactory.java:29)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.balthazargronon.RCTZeroconf.ZeroconfModule.getZeroconfImpl(ZeroconfModule.java:72)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.balthazargronon.RCTZeroconf.ZeroconfModule.stop(ZeroconfModule.java:64)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.balthazargronon.RCTZeroconf.ZeroconfModule.onCatalystInstanceDestroy(ZeroconfModule.java:108)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule.invalidate(BaseJavaModule.java:76)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:108)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:368)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
01-28 01:31:12.210 13740 13774 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by maximilize** [comment]
@balthazar Actually I was too quick with my PR. To ensure app stability, it makes sense to replace all `Exception`'s with `Throwable`.

**Comment by balthazar** [comment]
Guess I was too quick with my merge too 😄 Feel free to do another PR

**Comment by maximilize** [comment]
Done
